/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface_sistema_de_supermercado;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import sistema_de_supermercado.Produto;

/**
 *
 * @author Paulo
 */
public class Tela_Estoque extends javax.swing.JFrame {

    ArrayList<Produto> listaProd = new ArrayList<Produto>(); //Criando um ArrayList para os produtos (uma lista de produtos)
    boolean verificador = false;

    public Tela_Estoque() {
        Background b= new Background();
        initComponents();
        setLocationRelativeTo(null); //ela no centro
        setResizable(false); // bloqueia o maximizar 
        setDefaultCloseOperation( Tela_Estoque.DISPOSE_ON_CLOSE );
        startTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_prod = new javax.swing.JTable();
        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        c_nomeProd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Bttn_NovoProd = new javax.swing.JButton();
        C2_pesquisar = new javax.swing.JTextField();
        Bttn_pesquisar = new javax.swing.JButton();
        Bttn_sair = new javax.swing.JButton();
        Bttn_excluir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_prod1 = new javax.swing.JTable();
        c_codBarras = new javax.swing.JTextField();
        c_qtd = new javax.swing.JTextField();
        c_preço = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        tbl_prod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl_prod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Preço", "Qtd", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_prod);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(248, 148, 6));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jTabbedPane3.setBackground(new java.awt.Color(44, 62, 80));

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cod. Produto:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Produto:");

        c_nomeProd.setToolTipText("Nome do Produto");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantidade:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Preço:");

        Bttn_NovoProd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bttn_NovoProd.setText("Adicionar Novo");
        Bttn_NovoProd.setToolTipText("Cadastrar um novo produto no estoque");
        Bttn_NovoProd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Bttn_NovoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn_NovoProdActionPerformed(evt);
            }
        });

        C2_pesquisar.setToolTipText("Barra de pesquisa por nome");
        C2_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2_pesquisarActionPerformed(evt);
            }
        });
        C2_pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                C2_pesquisarKeyReleased(evt);
            }
        });

        Bttn_pesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bttn_pesquisar.setText("Pesquisar");
        Bttn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn_pesquisarActionPerformed(evt);
            }
        });

        Bttn_sair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bttn_sair.setText("Sair");
        Bttn_sair.setToolTipText("Sair da tela de Controle de Vendas");
        Bttn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn_sairActionPerformed(evt);
            }
        });

        Bttn_excluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bttn_excluir.setText("Excluir");
        Bttn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn_excluirActionPerformed(evt);
            }
        });

        tbl_prod1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl_prod1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Preço", "Qtd"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbl_prod1);
        if (tbl_prod1.getColumnModel().getColumnCount() > 0) {
            tbl_prod1.getColumnModel().getColumn(0).setResizable(false);
            tbl_prod1.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbl_prod1.getColumnModel().getColumn(1).setResizable(false);
            tbl_prod1.getColumnModel().getColumn(1).setPreferredWidth(150);
            tbl_prod1.getColumnModel().getColumn(2).setResizable(false);
            tbl_prod1.getColumnModel().getColumn(2).setPreferredWidth(50);
            tbl_prod1.getColumnModel().getColumn(3).setResizable(false);
            tbl_prod1.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(Bttn_excluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_preço, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_codBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_nomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Bttn_NovoProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bttn_sair)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(C2_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bttn_pesquisar)
                        .addGap(250, 250, 250))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(c_codBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(c_nomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c_preço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(c_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bttn_NovoProd)
                            .addComponent(Bttn_excluir)
                            .addComponent(Bttn_sair))
                        .addGap(506, 506, 506))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(C2_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bttn_pesquisar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane3.addTab("Estoque", jPanel3);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CONTROLE DE ESTOQUE E RELATÓRIO DE VENDAS ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void limpar_Campos() {
        c_codBarras.setText(null);
        c_nomeProd.setText(null);
        c_preço.setText(null);
        c_qtd.setText(null);
        
    }                                             

    private void C_PreçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_PreçoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_PreçoActionPerformed

    private void Bttn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn_excluirActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl_prod1.getModel();
        Produto p = new Produto();
        try {
            p.removerEst(tbl_prod1.getSelectedRow() + 1);
            model.removeRow(tbl_prod1.getSelectedRow());
            JOptionPane.showMessageDialog( null, "Produto Removido com sucesso", "Remoção bem sucedida", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            System.out.println("Erro: " + ex);;
        }
    }//GEN-LAST:event_Bttn_excluirActionPerformed

    private void Bttn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn_sairActionPerformed
        Background b = new Background();
        this.dispose();
    }//GEN-LAST:event_Bttn_sairActionPerformed

    private void C2_pesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_C2_pesquisarKeyReleased
        DefaultTableModel model = (DefaultTableModel) tbl_prod1.getModel();
        String search = C2_pesquisar.getText().toLowerCase();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tbl_prod1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_C2_pesquisarKeyReleased

    private void C2_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2_pesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C2_pesquisarActionPerformed

    private void Bttn_NovoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn_NovoProdActionPerformed
        addRowToJtable();
        Produto estoque = new Produto();
        estoque.setCodBarras(Integer.parseInt(c_codBarras.getText()));
        estoque.setNome(c_nomeProd.getText());
        estoque.setPreco(Double.parseDouble(c_preço.getText()));
        estoque.setQtd(Integer.parseInt(c_qtd.getText()));

        if (c_codBarras.getText().isEmpty()|| c_nomeProd.getText().isEmpty() || c_preço.getText().isEmpty() || c_qtd.getText().isEmpty()) {
            JOptionPane.showMessageDialog( // Caixa de mensagem
                null,// Janela da aplicação (opcional, pode ser null)
                "Por favor preencha todos os campos sobre o produto", // Mensagem
                "Erro de novo produto", // Título da caixa de mensagem
                JOptionPane.ERROR_MESSAGE); // Ícone da caixa de mensagem
        } else {
            JOptionPane.showMessageDialog(null, estoque.cadastrarEst());
        }
        limpar_Campos();
    }//GEN-LAST:event_Bttn_NovoProdActionPerformed

    private void Bttn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn_pesquisarActionPerformed
        
    }//GEN-LAST:event_Bttn_pesquisarActionPerformed
    
    public void startTable(){
        Scanner in;
        DefaultTableModel model = (DefaultTableModel) tbl_prod1.getModel();
        try{
            in = new Scanner(new File("Estoque.txt"));
            while(in.hasNextLine()){
                String s = in.nextLine();
                String[] sArray = s.split(";");

                listaProd.add(new Produto(Integer.parseInt(sArray[0]), sArray[1], Double.parseDouble(sArray[2]), Integer.parseInt(sArray[3])));
            }
        } catch(FileNotFoundException | NullPointerException ex){
            System.out.println("Erro: " + ex);
        }
        Object rowData[] = new Object[5];
        for(int i = 0; i < listaProd.size(); i++){
            rowData[0] = listaProd.get(i).getCodBarras();
            rowData[1] = listaProd.get(i).getNome();
            rowData[2] = listaProd.get(i).getPreco();
            rowData[3] = listaProd.get(i).getQtd();
            model.addRow(rowData);
        } 
    }
    
    public ArrayList listProd(){
        try{
            listaProd.add(new Produto(Integer.parseInt(c_codBarras.getText()), c_nomeProd.getText(), Double.parseDouble(c_preço.getText()), Integer.parseInt(c_qtd.getText())));
        } catch(NumberFormatException ex){
            System.out.println("Erro: " + ex);
        }
        
        return  listaProd;
    }
    
    public void addRowToJtable(){
        DefaultTableModel model = (DefaultTableModel) tbl_prod1.getModel();
        ArrayList<Produto> list = listProd();
        Object rowData[] = new Object[5];
        rowData[0] = Integer.parseInt(c_codBarras.getText());
        rowData[1] = c_nomeProd.getText();
        rowData[2] = Double.parseDouble(c_preço.getText());
        rowData[3] = Integer.parseInt(c_qtd.getText());
        model.addRow(rowData);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Estoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bttn_NovoProd;
    private javax.swing.JButton Bttn_excluir;
    private javax.swing.JButton Bttn_pesquisar;
    private javax.swing.JButton Bttn_sair;
    private javax.swing.JTextField C2_pesquisar;
    private javax.swing.JTextField c_codBarras;
    private javax.swing.JTextField c_nomeProd;
    private javax.swing.JTextField c_preço;
    private javax.swing.JTextField c_qtd;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable tbl_prod;
    private javax.swing.JTable tbl_prod1;
    // End of variables declaration//GEN-END:variables
}
